// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_example.proto

package lab.jrs.grpc.simpleexample;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleexample.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double num1 = 1;</code>
   * @return The num1.
   */
  double getNum1();

  /**
   * <code>double num2 = 2;</code>
   * @return The num2.
   */
  double getNum2();
}
