// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_example.proto

package lab.jrs.grpc.simpleexample;

/**
 * Protobuf type {@code simpleexample.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:simpleexample.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lab.jrs.grpc.simpleexample.SimpleExempleProto.internal_static_simpleexample_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lab.jrs.grpc.simpleexample.SimpleExempleProto.internal_static_simpleexample_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lab.jrs.grpc.simpleexample.Request.class, lab.jrs.grpc.simpleexample.Request.Builder.class);
  }

  public static final int NUM1_FIELD_NUMBER = 1;
  private double num1_ = 0D;
  /**
   * <code>double num1 = 1;</code>
   * @return The num1.
   */
  @java.lang.Override
  public double getNum1() {
    return num1_;
  }

  public static final int NUM2_FIELD_NUMBER = 2;
  private double num2_ = 0D;
  /**
   * <code>double num2 = 2;</code>
   * @return The num2.
   */
  @java.lang.Override
  public double getNum2() {
    return num2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(num1_) != 0) {
      output.writeDouble(1, num1_);
    }
    if (java.lang.Double.doubleToRawLongBits(num2_) != 0) {
      output.writeDouble(2, num2_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(num1_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, num1_);
    }
    if (java.lang.Double.doubleToRawLongBits(num2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, num2_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lab.jrs.grpc.simpleexample.Request)) {
      return super.equals(obj);
    }
    lab.jrs.grpc.simpleexample.Request other = (lab.jrs.grpc.simpleexample.Request) obj;

    if (java.lang.Double.doubleToLongBits(getNum1())
        != java.lang.Double.doubleToLongBits(
            other.getNum1())) return false;
    if (java.lang.Double.doubleToLongBits(getNum2())
        != java.lang.Double.doubleToLongBits(
            other.getNum2())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUM1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNum1()));
    hash = (37 * hash) + NUM2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNum2()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static lab.jrs.grpc.simpleexample.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static lab.jrs.grpc.simpleexample.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lab.jrs.grpc.simpleexample.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lab.jrs.grpc.simpleexample.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code simpleexample.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:simpleexample.Request)
      lab.jrs.grpc.simpleexample.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lab.jrs.grpc.simpleexample.SimpleExempleProto.internal_static_simpleexample_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lab.jrs.grpc.simpleexample.SimpleExempleProto.internal_static_simpleexample_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lab.jrs.grpc.simpleexample.Request.class, lab.jrs.grpc.simpleexample.Request.Builder.class);
    }

    // Construct using lab.jrs.grpc.simpleexample.Request.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      num1_ = 0D;
      num2_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lab.jrs.grpc.simpleexample.SimpleExempleProto.internal_static_simpleexample_Request_descriptor;
    }

    @java.lang.Override
    public lab.jrs.grpc.simpleexample.Request getDefaultInstanceForType() {
      return lab.jrs.grpc.simpleexample.Request.getDefaultInstance();
    }

    @java.lang.Override
    public lab.jrs.grpc.simpleexample.Request build() {
      lab.jrs.grpc.simpleexample.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public lab.jrs.grpc.simpleexample.Request buildPartial() {
      lab.jrs.grpc.simpleexample.Request result = new lab.jrs.grpc.simpleexample.Request(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(lab.jrs.grpc.simpleexample.Request result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.num1_ = num1_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.num2_ = num2_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lab.jrs.grpc.simpleexample.Request) {
        return mergeFrom((lab.jrs.grpc.simpleexample.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lab.jrs.grpc.simpleexample.Request other) {
      if (other == lab.jrs.grpc.simpleexample.Request.getDefaultInstance()) return this;
      if (other.getNum1() != 0D) {
        setNum1(other.getNum1());
      }
      if (other.getNum2() != 0D) {
        setNum2(other.getNum2());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              num1_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              num2_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double num1_ ;
    /**
     * <code>double num1 = 1;</code>
     * @return The num1.
     */
    @java.lang.Override
    public double getNum1() {
      return num1_;
    }
    /**
     * <code>double num1 = 1;</code>
     * @param value The num1 to set.
     * @return This builder for chaining.
     */
    public Builder setNum1(double value) {

      num1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double num1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      num1_ = 0D;
      onChanged();
      return this;
    }

    private double num2_ ;
    /**
     * <code>double num2 = 2;</code>
     * @return The num2.
     */
    @java.lang.Override
    public double getNum2() {
      return num2_;
    }
    /**
     * <code>double num2 = 2;</code>
     * @param value The num2 to set.
     * @return This builder for chaining.
     */
    public Builder setNum2(double value) {

      num2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double num2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum2() {
      bitField0_ = (bitField0_ & ~0x00000002);
      num2_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:simpleexample.Request)
  }

  // @@protoc_insertion_point(class_scope:simpleexample.Request)
  private static final lab.jrs.grpc.simpleexample.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lab.jrs.grpc.simpleexample.Request();
  }

  public static lab.jrs.grpc.simpleexample.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public lab.jrs.grpc.simpleexample.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

