// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_example.proto

package lab.jrs.grpc.simpleexample;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleexample.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
