// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_example.proto

package lab.jrs.grpc.simpleexample;

public final class SimpleExempleProto {
  private SimpleExempleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simpleexample_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simpleexample_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simpleexample_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simpleexample_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024simple_example.proto\022\rsimpleexample\"%\n" +
      "\007Request\022\014\n\004num1\030\001 \001(\001\022\014\n\004num2\030\002 \001(\001\"\032\n\010" +
      "Response\022\016\n\006result\030\001 \001(\t2I\n\rSimpleExempl" +
      "e\0228\n\003sum\022\026.simpleexample.Request\032\027.simpl" +
      "eexample.Response\"\000B2\n\032lab.jrs.grpc.simp" +
      "leexampleB\022SimpleExempleProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_simpleexample_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_simpleexample_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simpleexample_Request_descriptor,
        new java.lang.String[] { "Num1", "Num2", });
    internal_static_simpleexample_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_simpleexample_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simpleexample_Response_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
